language: go

go: master

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install: make dependencies

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: dist/rebaese*
    skip_cleanup: true
    file_glob: true
    on:
      tags: true
